.TH GOBYTE-CLI "1" "June 2016" "luckybit-cli 0.12"
.SH NAME
luckybit-cli \- a remote procedure call client for LuckyBit Core. 
.SH SYNOPSIS
luckybit-cli [options] <command> [params] \- Send command to LuckyBit Core. 
.TP
luckybit-cli [options] help \- Asks LuckyBit Core for a list of supported commands.
.SH DESCRIPTION
This manual page documents the luckybit-cli program. luckybit-cli is an RPC client used to send commands to LuckyBit Core.

.SH OPTIONS
.TP
\fB\-?\fR
Show possible options.

.SH "SEE ALSO"
\fBluckybitd\fP, \fBluckybit.conf\fP
.SH AUTHOR
This manual page was written by Ciemon Dunville <ciemon@gmail.com>. Permission is granted to copy, distribute and/or modify this document under the terms of the MIT License.

The complete text of the MIT License can be found on the web at \fIhttp://opensource.org/licenses/MIT\fP.
